name: Build and Test a Javascript App

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
        description: The version of Node to use (e.g. '18.x')
      upload-artifact:
        required: false
        type: boolean
        description: Whether an artefact should be uploaded or not
        default: false
      artifact-path:
        required: false
        type: string
        description: Location of the build output
        default: "./build"
      artifact-name:
        required: false
        type: string
        description: The name of the artifact
        default: javascript-app-artifact
    outputs:
      artifact-uploaded:
        value: ${{ jobs.build-app-and-test.outputs.artifact-uploaded }}
        description: Flag to determine if artifact was uploaded or not

jobs:
  build-app-and-test:
    runs-on: ubuntu-latest
    name: Build and Test for Node version ${{ inputs.node-version }}
    outputs:
      artifact-uploaded: ${{ steps.set-artifact-uploaded.outputs.artifact-uploaded }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set-Up Node Environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      - name: Build App
        run: |
          npm i
          npm run build

      - name: Run Tests
        run: |
          npm run test

      - name: Upload Artifact for Node version ${{ inputs.node-version }}
        uses: actions/upload-artifact@v4.3.1
        if: ${{ inputs.upload-artifact }}
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
          if-no-files-found: error

      - name: Set Artifact Uploaded Flag
        if: ${{ inputs.upload-artifact }}
        id: set-artifact-uploaded
        shell: pwsh
        run: |
          "artifact-uploaded=true" >> $env:GITHUB_OUTPUT
