name: Build and Deploy React Sample App

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - "!terraform/**"
  pull_request:
    branches: ["master"]
    paths:
      - "!terraform/**"

jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        upload-artifact: [false]
        include:
          - node-version: 18.x
            upload-artifact: true
        exclude:
          - node-version: 18.x
            upload-artifact: false
    uses: ./.github/workflows/build-javascript-app-with-npm.yml
    with:
      node-version: ${{ matrix. node-version }}
      upload-artifact: ${{ matrix.upload-artifact }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-javascript-app.yml
    secrets:
      deploy-token: ${{ secrets.AZ_DEPLOY_TOKEN }}
