name: Build and Deploy React Sample App

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - "!terraform/**"
  pull_request:
    branches: ["master"]
    paths:
      - "!terraform/**"

jobs:
  build:
    name: Build the React App
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        experimental: [false]
        include:
          - node-version: 20.x
            experimental: true
        exclude:
          - node-version: 20.x
            experimental: false

    steps:
      - name: Get Node Version
        id: get-parsed-version
        shell: pwsh
        run: |
          $ParsedVersion = "${{ matrix.node-version }}" -replace '[^0-9]', ''
          "parsed-version=$ParsedVersion" >> $env:GITHUB_OUTPUT

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Build
        run: |
          npm i
          npm run build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        if: ${{ steps.get-parsed-version.outputs.parsed-version == '18' }}
        with:
          name: react-app-sample
          path: "./build"
          if-no-files-found: error

  deploy:
    needs: build
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    name: Deploy the React Sample App to Azure
    steps:
      - name: Download the Artifact
        uses: actions/download-artifact@v4.1.2
        with:
          name: react-app-sample

      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          app_location: "/"
          output_location: "/dist"
          azure_static_web_apps_api_token: ${{ secrets.AZ_DEPLOY_TOKEN }}
