name: Build and Deploy React Sample App

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - "!terraform/**"
  pull_request:
    branches: ["master"]
    paths:
      - "!terraform/**"

jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        upload-artifact: [false]
        include:
          - node-version: 18.x
            upload-artifact: true
        exclude:
          - node-version: 18.x
            upload-artifact: false
    uses: ./.github/workflows/build-and-test-javascript-app.yml
    with:
      env-short-code: smk
      node-version: ${{ matrix. node-version }}
      upload-artifact: ${{ matrix.upload-artifact }}

  e2e-tests:
    name: End-to-End Tests
    if: ${{ needs.build.outputs.artifact-uploaded }}
    needs: build
    uses: ./.github/workflows/run-e2e-tests.yml
    with:
      env-short-code: smk

  deploy:
    name: Deploy to Azure
    needs: e2e-tests
    uses: ./.github/workflows/deploy-javascript-app.yml
    with:
      env-short-code: smk
    secrets:
      deploy-token: ${{ secrets.AZ_DEPLOY_TOKEN }}
