name: Build and Deploy React Sample App

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - "!terraform/**"
  pull_request:
    branches: ["master"]
    paths:
      - "!terraform/**"

jobs:
  ci-cd:
    uses: ./.github/workflows/ci-cd-workflow.yml
    strategy:
      matrix:
        env-short-code: ["smk", "uat"]
      fail-fast: true
      max-parallel: 1
    with:
      env-short-code: ${{ matrix.env-short-code }}
      node-version: 18.x
      sentinel-value: ${{ vars.SENTINEL }}
    secrets:
      deploy-token: ${{ secrets.AZ_DEPLOY_TOKEN }}
