name: Build and Deploy React Sample App

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - "!terraform/**"
  pull_request:
    branches: ["master"]
    paths:
      - "!terraform/**"

jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        upload-artifact: [false]
        include:
          - node-version: 18.x
            upload-artifact: true
        exclude:
          - node-version: 18.x
            upload-artifact: false
    uses: ./.github/workflows/build-javascript-app-with-npm.yml
    with:
      node-version: ${{ matrix. node-version }}
      upload-artifact: ${{ matrix.upload-artifact }}

  e2e-tests:
    needs: build
    name: End-to-End Tests with Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Artifact
        uses: actions/download-artifact@v4.1.2
        with:
          name: javascript-app-artifact
          path: build

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: chrome

  deploy:
    needs: e2e-tests
    uses: ./.github/workflows/deploy-javascript-app.yml
    secrets:
      deploy-token: ${{ secrets.AZ_DEPLOY_TOKEN }}
