name: Deploy a Javascript App to Azure

on:
  workflow_call:
    inputs:
      artifact-output-location:
        required: false
        type: string
        description: The location of the build output
        default: "/build"
      app-location:
        required: false
        type: string
        description: The location of the application once the artifact is uploaded
        default: "/"
    secrets:
      deploy-token:
        required: true
        description: The token required to deploy the app to Azure

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Azure

    steps:
      - name: Download the Artifact
        uses: actions/download-artifact@v4.1.2
        with:
          name: javascript-app-artifact

      - name: Deploy to Static Web App
        uses: azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          app_location: ${{ inputs.app-location }}
          output_location: ${{ inputs.artifact-output-location }}
          azure_static_web_apps_api_token: ${{ secrets.deploy-token }}
