name: Run End-to-End Tests

on:
  workflow_call:
    inputs:
      artifact-name:
        required: false
        type: string
        description: The name of the artifact
        default: javascript-app-artifact

jobs:
  e2e-tests:
    name: End-to-End Tests with Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Artifact
        uses: actions/download-artifact@v4.1.2
        with:
          name: ${{ inputs.artifact-name }}

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: chrome
